# Generated by Django 4.2.5 on 2023-09-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
