# Generated by Django 4.2.5 on 2023-09-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
