# Generated by Django 4.2.5 on 2023-09-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
